language: ruby

matrix:
  include:
    - os: linux
      rvm: 1.9.3
    - os: linux
      rvm: 2.4
    - os: linux
      rvm: 2.5
    - os: osx
      rvm: 2.5

script:
  - bundle exec ruby ext/clipper/extconf.rb
  - make install
  - bundle exec rake test --trace
